<script lang="ts">
	import { APP_NAME } from '$lib/branding';
</script>

<svelte:head>
	<title>terms of service - {APP_NAME}</title>
	<meta name="description" content="Terms of Service for {APP_NAME}" />
</svelte:head>

<div class="legal-container">
	<article class="legal-content">
		<h1>terms of service</h1>
		<p class="last-updated">last updated: december 10, 2025</p>

		<p class="intro">
			{APP_NAME} is a music streaming platform built on the AT Protocol. by using our service,
			you agree to these terms. if you don't agree, please don't use the service.
		</p>

		<nav class="toc">
			<h2>contents</h2>
			<ol>
				<li><a href="#definitions">definitions</a></li>
				<li><a href="#account">account & authentication</a></li>
				<li><a href="#artist-terms">artist terms</a></li>
				<li><a href="#listener-terms">listener terms</a></li>
				<li><a href="#content-policy">content policy</a></li>
				<li><a href="#dmca">copyright & DMCA</a></li>
				<li><a href="#termination">termination</a></li>
				<li><a href="#disclaimers">disclaimers & liability</a></li>
				<li><a href="#disputes">disputes & arbitration</a></li>
				<li><a href="#changes">changes to terms</a></li>
			</ol>
		</nav>

		<section id="definitions">
			<h2>1. definitions</h2>
			<ul>
				<li><strong>"Service"</strong> refers to {APP_NAME} and all related features, APIs, and infrastructure.</li>
				<li><strong>"Content"</strong> means audio files, artwork, metadata, and any other material uploaded to the Service.</li>
				<li><strong>"Artist"</strong> is any user who uploads Content to the Service.</li>
				<li><strong>"Listener"</strong> is any user who streams Content.</li>
				<li><strong>"DID"</strong> (Decentralized Identifier) is your unique identity on the AT Protocol.</li>
				<li><strong>"PDS"</strong> (Personal Data Server) is where your AT Protocol data is stored.</li>
			</ul>
		</section>

		<section id="account">
			<h2>2. account & authentication</h2>
			<p>
				{APP_NAME} uses AT Protocol OAuth for authentication. your identity is your DID, not
				an account we control. we do not store passwords.
			</p>
			<p>
				<strong>important:</strong> {APP_NAME} controls access to our infrastructure, not your
				identity. if we terminate your access, your DID and data on your PDS remain yours.
				we can only remove your content from our servers and deny you access to our features.
			</p>
			<p>
				you are responsible for maintaining the security of your AT Protocol credentials and
				any devices used to access the Service.
			</p>
		</section>

		<section id="artist-terms">
			<h2>3. artist terms</h2>

			<h3>3.1 license grant</h3>
			<p>
				by uploading Content, you grant {APP_NAME} a non-exclusive, worldwide, royalty-free,
				sublicensable license to:
			</p>
			<ul>
				<li>reproduce, distribute, and publicly perform your Content</li>
				<li>create derivative works (e.g., transcoding audio formats, generating thumbnails)</li>
				<li>cache, index, and retransmit your Content as necessary for the AT Protocol</li>
				<li>sublicense these rights to infrastructure partners (CDNs) solely to operate the Service</li>
			</ul>
			<p>
				you retain full ownership of your Content. this license terminates when you remove
				your Content from the Service.
			</p>

			<h3>3.2 ownership warranty</h3>
			<p>you represent and warrant that:</p>
			<ul>
				<li>you own or control all rights to the Content you upload</li>
				<li>you have cleared all necessary rights, including master recording, composition, and samples</li>
				<li>your Content does not infringe any third party's intellectual property rights</li>
				<li>if your Content was generated by AI, you have the legal right to distribute it</li>
			</ul>
		</section>

		<section id="listener-terms">
			<h2>4. listener terms</h2>

			<h3>4.1 streaming license</h3>
			<p>
				when you stream Content, you receive a <strong>limited, non-exclusive, non-transferable
				license</strong> to stream that Content via the Service for personal, non-commercial use.
			</p>

			<h3>4.2 prohibited uses</h3>
			<p>you agree not to:</p>
			<ul>
				<li>download, rip, or capture audio streams ("stream ripping")</li>
				<li>use automated tools to access the Service (bots, scrapers)</li>
				<li>circumvent access controls or DRM</li>
				<li>use Content to train machine learning or AI models without explicit permission from the rights holder</li>
			</ul>
		</section>

		<section id="content-policy">
			<h2>5. content policy</h2>

			<h3>5.1 prohibited content</h3>
			<p>you may not upload content that:</p>
			<ul>
				<li>infringes copyright, trademark, or other intellectual property rights</li>
				<li>promotes hate, violence, or discrimination</li>
				<li>is illegal in the United States</li>
			</ul>

			<h3>5.2 moderation</h3>
			<p>
				we use automated and manual moderation to detect prohibited content. we may remove
				content, suspend access, or terminate accounts without prior notice if we
				reasonably believe a violation has occurred.
			</p>
		</section>

		<section id="dmca">
			<h2>6. copyright & DMCA</h2>

			<h3>6.1 DMCA compliance</h3>
			<p>
				{APP_NAME} complies with the Digital Millennium Copyright Act (DMCA). we will respond
				to valid takedown notices and remove or disable access to infringing material.
			</p>

			<h3>6.2 designated agent</h3>
			<p>our designated DMCA agent is:</p>
			<address class="dmca-agent">
				Nathan Nowack<br />
				DMCA Registration: DMCA-1069186<br />
				Email: <a href="mailto:plyrdotfm@proton.me">plyrdotfm@proton.me</a>
			</address>

			<h3>6.3 takedown notice requirements</h3>
			<p>a valid DMCA notice must include:</p>
			<ol>
				<li>your physical or electronic signature</li>
				<li>identification of the copyrighted work claimed to be infringed</li>
				<li>identification of the infringing material with enough detail to locate it (URL)</li>
				<li>your contact information (address, phone, email)</li>
				<li>a statement that you have a good faith belief the use is not authorized</li>
				<li>a statement, under penalty of perjury, that the information is accurate and you are authorized to act on behalf of the copyright owner</li>
			</ol>

			<h3>6.4 counter-notification</h3>
			<p>
				if you believe your content was wrongly removed, you may file a counter-notification
				with the same information plus a statement consenting to jurisdiction in federal court.
			</p>

			<h3>6.5 repeat infringers</h3>
			<p>
				we terminate the accounts of repeat infringers. <strong>three valid DMCA strikes results in
				permanent removal from the Service.</strong>
			</p>

			<h3>6.6 AT Protocol limitation</h3>
			<p>
				<strong>important:</strong> {APP_NAME} can only remove content from our servers. we
				cannot delete content that has been published to other AT Protocol servers or your
				PDS. our takedown applies only to the {APP_NAME} interface and infrastructure.
			</p>
		</section>

		<section id="termination">
			<h2>7. termination</h2>
			<p>
				we may suspend or terminate your access at any time, for any reason, including
				violation of these terms.
			</p>
			<p>upon termination:</p>
			<ul>
				<li>your content is delisted from {APP_NAME}</li>
				<li>your DID and PDS data remain yours (we do not control them)</li>
			</ul>
			<p>
				you may delete your account at any time through the portal settings. account deletion
				removes your content from {APP_NAME} but does not affect data on the AT Protocol network.
			</p>
		</section>

		<section id="disclaimers">
			<h2>8. disclaimers & liability</h2>

			<h3>8.1 "as is" service</h3>
			<p>
				the Service is provided "as is" and "as available" without warranties of any kind,
				express or implied. we do not guarantee uptime, availability, or that the Service
				will be error-free.
			</p>

			<h3>8.2 limitation of liability</h3>
			<p>
				to the maximum extent permitted by law, {APP_NAME} and its operators shall not be
				liable for any indirect, incidental, special, consequential, or punitive damages,
				or any loss of profits or revenues, whether incurred directly or indirectly.
			</p>
			<p>
				our total liability for any claim arising from these terms or your use of the Service
				is limited to <strong>$100 USD</strong> or the amount you paid us in the past 12
				months, whichever is greater.
			</p>

			<h3>8.3 indemnification</h3>
			<p>
				you agree to indemnify and hold harmless {APP_NAME}, its operators, and their
				affiliates from any claims, damages, losses, liabilities, and expenses (including
				legal fees) arising from:
			</p>
			<ul>
				<li>your use of the Service</li>
				<li>your violation of these terms</li>
				<li>your violation of any third-party rights, including intellectual property</li>
				<li>content you upload through the Service</li>
			</ul>
		</section>

		<section id="disputes">
			<h2>9. disputes & arbitration</h2>

			<h3>9.1 governing law</h3>
			<p>
				these terms are governed by the laws of the State of Delaware, United States, without
				regard to conflict of law principles.
			</p>

			<h3>9.2 binding arbitration</h3>
			<p>
				<strong>please read carefully:</strong> you agree that any dispute arising from these
				terms or your use of the Service will be resolved through binding arbitration
				administered by the American Arbitration Association (AAA) under its Commercial
				Arbitration Rules.
			</p>
			<p>
				arbitration will be conducted in English, and the arbitrator's decision will be final
				and binding. judgment may be entered in any court of competent jurisdiction.
			</p>

			<h3>9.3 class action waiver</h3>
			<p>
				<strong>you waive any right to participate in a class action lawsuit or class-wide
				arbitration.</strong> all disputes must be brought in your individual capacity.
			</p>

			<h3>9.4 exceptions</h3>
			<p>
				notwithstanding the above, either party may seek injunctive relief in court for
				intellectual property infringement or unauthorized access to the Service.
			</p>

			<h3>9.5 severability</h3>
			<p>
				if the arbitration agreement is found unenforceable (e.g., in certain EU jurisdictions),
				the remaining terms still apply. disputes would then be resolved in the courts of Delaware.
			</p>
		</section>

		<section id="changes">
			<h2>10. changes to terms</h2>
			<p>
				we may update these terms from time to time. material changes will be announced via
				the Service or email with at least 30 days' notice before taking effect.
			</p>
			<p>
				continued use of the Service after changes take effect constitutes acceptance of the
				new terms. if you disagree, you should stop using the Service and delete your account.
			</p>
		</section>

		<section class="contact">
			<h2>contact</h2>
			<p>
				questions about these terms? contact us at
				<a href="mailto:plyrdotfm@proton.me">plyrdotfm@proton.me</a>.
			</p>
		</section>
	</article>
</div>

<style>
	.legal-container {
		max-width: 800px;
		margin: 0 auto;
		padding: 2rem 1.5rem 6rem;
	}

	.legal-content {
		color: var(--text-primary);
		line-height: 1.7;
	}

	h1 {
		font-size: 2rem;
		margin: 0 0 0.5rem 0;
		color: var(--text-primary);
	}

	.last-updated {
		color: var(--text-tertiary);
		font-size: 0.9rem;
		margin: 0 0 2rem 0;
	}

	.intro {
		font-size: 1.1rem;
		color: var(--text-secondary);
		margin-bottom: 2rem;
		padding-bottom: 2rem;
		border-bottom: 1px solid var(--border-subtle);
	}

	.toc {
		background: var(--bg-secondary);
		border: 1px solid var(--border-subtle);
		border-radius: 8px;
		padding: 1.5rem;
		margin-bottom: 3rem;
	}

	.toc h2 {
		font-size: 1rem;
		margin: 0 0 1rem 0;
		color: var(--text-secondary);
		text-transform: lowercase;
	}

	.toc ol {
		margin: 0;
		padding-left: 1.5rem;
	}

	.toc li {
		margin-bottom: 0.5rem;
	}

	.toc a {
		color: var(--accent);
		text-decoration: none;
	}

	.toc a:hover {
		text-decoration: underline;
	}

	section {
		margin-bottom: 3rem;
	}

	h2 {
		font-size: 1.3rem;
		margin: 0 0 1rem 0;
		color: var(--text-primary);
		padding-top: 1rem;
		border-top: 1px solid var(--border-subtle);
	}

	h3 {
		font-size: 1.1rem;
		margin: 1.5rem 0 0.75rem 0;
		color: var(--text-primary);
	}

	p {
		margin: 0 0 1rem 0;
		color: var(--text-secondary);
	}

	ul, ol {
		margin: 0 0 1rem 0;
		padding-left: 1.5rem;
		color: var(--text-secondary);
	}

	li {
		margin-bottom: 0.5rem;
	}

	strong {
		color: var(--text-primary);
	}

	a {
		color: var(--accent);
		text-decoration: none;
	}

	a:hover {
		text-decoration: underline;
	}

	.dmca-agent {
		background: var(--bg-secondary);
		border: 1px solid var(--border-subtle);
		border-radius: 4px;
		padding: 1rem;
		font-style: normal;
		color: var(--text-secondary);
		margin: 1rem 0;
	}

	.contact {
		background: var(--bg-secondary);
		border: 1px solid var(--border-subtle);
		border-radius: 8px;
		padding: 1.5rem;
	}

	.contact h2 {
		border-top: none;
		padding-top: 0;
		margin-top: 0;
	}

	.contact p {
		margin: 0;
	}

	@media (max-width: 600px) {
		.legal-container {
			padding: 1.5rem 1rem 6rem;
		}

		h1 {
			font-size: 1.5rem;
		}

		h2 {
			font-size: 1.15rem;
		}

		h3 {
			font-size: 1rem;
		}
	}
</style>
