"""add user preferences table

Revision ID: 06daebe03213
Revises: 547a171dfd11
Create Date: 2025-11-02 12:21:41.790953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06daebe03213'
down_revision: Union[str, Sequence[str], None] = '547a171dfd11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tracks', 'artists', ['artist_did'], ['did'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    # ### end Alembic commands ###
