"""add track_likes table for indexing ATProto like records

Revision ID: 32c17ef04e98
Revises: 2d9a62e170d6
Create Date: 2025-11-11 12:11:10.140510

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32c17ef04e98"
down_revision: str | Sequence[str] | None = "2d9a62e170d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "track_likes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("user_did", sa.String(), nullable=False),
        sa.Column("atproto_like_uri", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id", "user_did", name="uq_track_user_like"),
        sa.UniqueConstraint("atproto_like_uri"),
    )
    op.create_index(
        op.f("ix_track_likes_atproto_like_uri"),
        "track_likes",
        ["atproto_like_uri"],
        unique=True,
    )
    op.create_index(op.f("ix_track_likes_id"), "track_likes", ["id"], unique=False)
    op.create_index(
        op.f("ix_track_likes_track_id"), "track_likes", ["track_id"], unique=False
    )
    op.create_index(
        op.f("ix_track_likes_user_did"), "track_likes", ["user_did"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_track_likes_user_did"), table_name="track_likes")
    op.drop_index(op.f("ix_track_likes_track_id"), table_name="track_likes")
    op.drop_index(op.f("ix_track_likes_id"), table_name="track_likes")
    op.drop_index(op.f("ix_track_likes_atproto_like_uri"), table_name="track_likes")
    op.drop_table("track_likes")
    # ### end Alembic commands ###
