"""add image_id to tracks

Revision ID: 36868f2c20e5
Revises: ba46ea4ba64e
Create Date: 2025-11-09 14:34:08.434907

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36868f2c20e5"
down_revision: str | Sequence[str] | None = "ba46ea4ba64e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tracks", sa.Column("image_id", sa.String(), nullable=True))
    op.create_index(op.f("ix_tracks_image_id"), "tracks", ["image_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracks_image_id"), table_name="tracks")
    op.drop_column("tracks", "image_id")
    # ### end Alembic commands ###
