"""add exchange_tokens table for secure OAuth callback

Revision ID: ec40ac6453bc
Revises: 846cc6b867b8
Create Date: 2025-11-03 10:15:32.856846

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ec40ac6453bc"
down_revision: str | Sequence[str] | None = "846cc6b867b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
