set shell := ["bash", "-eu", "-o", "pipefail", "-c"]
default := "run"

alias r := run
alias b := build

run:
    TRANSCODER_HOST="${TRANSCODER_HOST:-127.0.0.1}" \
    TRANSCODER_PORT="${TRANSCODER_PORT:-8082}" \
    cargo watch -x run

build:
    cargo build --release

check:
    cargo check

fmt:
    cargo fmt

clippy:
    cargo clippy --all-targets --all-features

image tag="plyr-transcoder:local":
    docker build -t {{tag}} .

docker-run TAG="plyr-transcoder:local" PORT="8082":
    docker run --rm -p {{PORT}}:8080 {{TAG}}

fly ARGS="":
    fly deploy --config fly.toml {{ARGS}}
