"""add oauth_states table

Revision ID: 846cc6b867b8
Revises: 31e69ba0c570
Create Date: 2025-11-02 20:53:02.843233

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "846cc6b867b8"
down_revision: str | Sequence[str] | None = "31e69ba0c570"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_states",
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("pkce_verifier", sa.String(), nullable=False),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("authserver_iss", sa.String(), nullable=False),
        sa.Column("dpop_private_key_pem", sa.Text(), nullable=False),
        sa.Column("dpop_authserver_nonce", sa.String(), nullable=False),
        sa.Column("did", sa.String(), nullable=True),
        sa.Column("handle", sa.String(), nullable=True),
        sa.Column("pds_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("state"),
    )
    op.create_index(
        op.f("ix_oauth_states_created_at"), "oauth_states", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_states_state"), "oauth_states", ["state"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_oauth_states_state"), table_name="oauth_states")
    op.drop_index(op.f("ix_oauth_states_created_at"), table_name="oauth_states")
    op.drop_table("oauth_states")
    # ### end Alembic commands ###
