"""add artist account_status

Revision ID: 82a75e0ecf9f
Revises: 28201f72683d
Create Date: 2026-07-29 13:06:09.076534

autogenerated against a drifted local dev database, then trimmed to the one
intended change. the generated version also proposed dropping the `api_keys`
and `pending_account_creations` tables and several trigram indexes — all local
drift, none of it wanted.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82a75e0ecf9f"
down_revision: str | Sequence[str] | None = "28201f72683d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("artists", sa.Column("account_status", sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("artists", "account_status")
