"""internal relay modules."""

from backend._internal.auth import (
    DeveloperToken,
    LinkedAccount,
    PendingAddAccountData,
    PendingDevTokenData,
    PendingScopeUpgradeData,
    Session,
    check_artist_profile_exists,
    consume_exchange_token,
    create_exchange_token,
    create_session,
    delete_pending_add_account,
    delete_pending_dev_token,
    delete_pending_scope_upgrade,
    delete_session,
    ensure_artist_exists,
    get_oauth_client,
    get_optional_session,
    get_or_create_group_id,
    get_pending_add_account,
    get_pending_dev_token,
    get_pending_scope_upgrade,
    get_session,
    get_session_group,
    handle_oauth_callback,
    list_developer_tokens,
    remove_account_from_group,
    require_artist_profile,
    require_auth,
    revoke_developer_token,
    save_pending_add_account,
    save_pending_dev_token,
    save_pending_scope_upgrade,
    start_oauth_flow,
    start_oauth_flow_with_scopes,
    switch_active_account,
    update_session_tokens,
)
from backend._internal.constellation import get_like_count_safe
from backend._internal.feature_flags import KNOWN_FLAGS, has_flag
from backend._internal.notifications import notification_service
from backend._internal.now_playing import now_playing_service
from backend._internal.queue import queue_service
from backend._internal.atprotofans import get_supported_artists, validate_supporter

__all__ = [
    "KNOWN_FLAGS",
    "DeveloperToken",
    "LinkedAccount",
    "PendingAddAccountData",
    "PendingDevTokenData",
    "PendingScopeUpgradeData",
    "Session",
    "check_artist_profile_exists",
    "consume_exchange_token",
    "create_exchange_token",
    "create_session",
    "delete_pending_add_account",
    "delete_pending_dev_token",
    "delete_pending_scope_upgrade",
    "delete_session",
    "ensure_artist_exists",
    "get_like_count_safe",
    "get_oauth_client",
    "get_optional_session",
    "get_or_create_group_id",
    "get_pending_add_account",
    "get_pending_dev_token",
    "get_pending_scope_upgrade",
    "get_session",
    "get_session_group",
    "get_supported_artists",
    "handle_oauth_callback",
    "has_flag",
    "list_developer_tokens",
    "notification_service",
    "now_playing_service",
    "queue_service",
    "remove_account_from_group",
    "require_artist_profile",
    "require_auth",
    "revoke_developer_token",
    "save_pending_add_account",
    "save_pending_dev_token",
    "save_pending_scope_upgrade",
    "start_oauth_flow",
    "start_oauth_flow_with_scopes",
    "switch_active_account",
    "update_session_tokens",
    "validate_supporter",
]
